### ISSUE TITLE
终端打开emacs，并开启c-mode，发现括号自动补全失效

### ISSUE THREAD

**Issue by ly0303521** [redguardtoo/emacs.d#295]
如题所示错误，但是如果打开一个现成的C文件又不会出现上述问题

**Comment by redguardtoo** [comment]
save your content to a real file at first,

check init-cc-mode.el, I disable those plugins when there is no real file corresponding to current file.

The reason is some plugins will load c-mode to render some c code snippet to html.

Those plugins need only syntax highlight, so extra plugins will slow down the rendering process.
