### ISSUE TITLE
which-function-mode doesn't work

### ISSUE THREAD

**Issue by nshigit** [redguardtoo/emacs.d#415]
OS: Linux-Mint 17.2 x86-64
Emacs: GNU Emacs 24.3.1
Emacs.d: 2.1 

I try to open 'which-function-mode' in cc-mode, but it doesn't work.
Could you give me some tips about showing current function name in the mode-line or head-line?

**Comment by redguardtoo** [comment]
c or c++? give me some sample file?

**Comment by nshigit** [comment]
I have tried the attached files with emacs by ALT-x which-function-mode to enable which-function-mode. But I can't find the function name on mode-line.

BTW, I also tried to add (which-function-mode 1) at line 94 of file list/init-cc-mode.el to  enable which-function-mode automaticly when c or c++ file is modified. But it only worked for c++ file(.cc).

Date: Sun, 14 Feb 2016 05:46:45 -0800

**Comment by redguardtoo** [comment]
`M-x popup-which-function`. This function is written by me. It always works because it re-scan imenu at the beginning and has better UI.

In my vague memory (I don't remember details so I could be wrong), by default mode-line fails to display function name because some modeline format issue (not my setup, it just doesn't work in vanilla emacs), you can see https://www.emacswiki.org/emacs/WhichFuncMode for more info.

**Comment by redguardtoo** [comment]
BTW, you could read my "Master Emacs in one year", there is NO reason to use UI of old plugin. Regard it as collection of APIs instead.

**Comment by nshigit** [comment]
Thanks. popup-which-function works fine. I have read the Chinese version "Master Emacs in one year" serveral times in last year. It is such a cool article I ever read about emacs. 

Date: Sun, 14 Feb 2016 21:37:49 -0800
