### ISSUE TITLE
How about considering add smex  again?

### ISSUE THREAD

**Issue by lipanXJ** [redguardtoo/emacs.d#496]
If use smex,the history command will display in the top,i do think it's useful sometimes,what your opinion about it?

**Comment by redguardtoo** [comment]
Thanks. I also found this issue.

It turns out that `smex` will be used by `counsel-M-x` to remember command history.

Now I use `counsel-M-x` by default but `smex` is also installed. So smex could provide history to counsel-M-x.

If you still want to use smex, you can also `(setq my-use-smex t)` in `~/.custom.el`

d99d41f smex is still useful when `counsel-M-x` (Chen Bin)
