### ISSUE TITLE
Evil mode: Can't repeat the searched char within the line started with f/F/t/T

### ISSUE THREAD

**Issue by amittendulkar** [redguardtoo/emacs.d#525]
This is more of help needed than an issue. In Vim there is a great way to search a particular char forward/backward in the same line with f/F or t/T. This works in Evil mode. However, in Vim I could continue the same search using ; (semicolon) key. This key doesn't work in Emacs Evil mode. Is there any workaround other than pressing the char and f/F or t/T again?

**Comment by redguardtoo** [comment]
Because I use `;` as evil leader key.
see https://github.com/redguardtoo/emacs.d/blob/master/lisp/init-evil.el
You can comment that part

Please note Emacs+Evil gives you more power. For example, in my setup, press `;;` equals `M-x  avy-goto-char-timer`. Please read http://emacsredux.com/blog/2015/07/19/ace-jump-mode-is-dead-long-live-avy/

Anyway, you have got full freedom to map any key to any command.

**Comment by amittendulkar** [comment]
Thanks for the info/links and pulling me out of the stone age ;)
