### ISSUE TITLE
flymake configuration error

### ISSUE THREAD

**Issue by viscroad** [redguardtoo/emacs.d#633]
I encounter one problem when running emacs flymake.

When I run your config, all work fine when editing c/c++ file.
I got error when editing c/c++ file under emacs 25 without your config.

**Flymake: Configuration error has occurred while running (make -s -C ../../ CHK_SOURCES=hello_flymake.c SYNTAX_CHECK_MODE=1 check-syntax). Flymake will be switched off. **

if I create a Makefile, it works. But emacs works without Makefile under your config.

Would you please help me how do you fix this error in your config?

Thanks!

**Comment by redguardtoo** [comment]
You can comment out `(flymake-mode 1)` in `init-cc-mode.el`.

I used flymake instead of flycheck because I used to support Emacs v24.3. But since year 2018, I will support emacs v24.4 only.

So I suggest disabling flymake and install flycheck (flymake supports all versions of Emacs. Flycheck requires Emacs 24.4).

**Comment by viscroad** [comment]
thanks. close this thread.
