### ISSUE TITLE
Aspell 0.60.8 will have direct support for camelCase words

### ISSUE THREAD

**Issue by kevina** [redguardtoo/emacs.d#796]
I found you blog post and thought you might like to know that Aspell 0.60.8 will have direct support for checking camel case words so the `--run-together` option should no longer be needed.  I am actually quite surprised anyone used the `--run-together` option.  The suggestions when `--run-together` is used are not very good.  When you use `--camel-case` you should be able to get reasonable suggestions for misspellings when camel case is used, without a lot of additional noise when words don't use camel case (unlike the case when the  `--run-together` option is used).

You can try it out now at https://github.com/GNUAspell/aspell/pull/574, this will likely get merged sometime in the next week or two.  I am eager to know what you think of it.

**Comment by redguardtoo** [comment]
I sovled this problem ages ago using pure emacs lisp, see https://github.com/redguardtoo/wucuo

So my setup can check camel case word whatever spell check cli program is. could be aspell, could be hunspell.

I know the limitation of aspell because I read its c++ code. See http://blog.binchen.org/posts/how-to-spell-check-functionvariable-in-emacs.html

**Comment by redguardtoo** [comment]
@kevina, I got below error when compiling camel-case branche code,
![image](https://user-images.githubusercontent.com/184553/64076302-87010680-cd06-11e9-83e2-13d457e731ce.png)

**Comment by kevina** [comment]
It looks like some generated files where not updated.  Try rerunning `autogen` as indicated in the README.
