### ISSUE TITLE
Error running timer ‘ivy--exhibit’: (void-function nil)

### ISSUE THREAD

**Issue by swustcfl** [redguardtoo/emacs.d#811]
1: git clean -dfx
2: start emacs 26， M-x counsel-rg   then  throw this error 
Thank you

**Comment by redguardtoo** [comment]
Make sure `counsel`, `ivy`, `swiper` is using stable version.
I guess the problem is some 3rd packages dependent on counsel using unstable version. So my `counsel` is unstable version but `ivy` is stable. So there is version conflict.

969cf413 counsel packages should be stable version (Chen Bin)

**Comment by redguardtoo** [comment]
The root cause is my package filter is not correctly upgraded, so when you do the full package upgrade, package `counsel`, `evil` will be upgraded to unstable version.

It's fixed in 969cf413.

To fix this issue, 
- Remove unstable pacakges, `cd ~/.emacs.d/elpa/ && rm --rf counsel-20* evil-20*`
- download `evil` and `counsel` tar files from https://stable.melpa.org, run `M-x package-install-file` to install local tar
