### ISSUE TITLE
如何能配置出顺手的 Web 开发环境

### ISSUE THREAD

**Issue by JMwill** [redguardtoo/emacs.d#827]
# 开发环境
1. 13-inch MacBook Pro
2. Emacs-cocoa 版 26.3(9.0)
3. 日常开发使用到的库 React、Vue.js 以及一些常用工具库，偶尔编写 Node.js、Python
4. 终端模拟器：iTerm 2，偶尔使用终端复用软件：tmux
5. Shell：zsh + oh-my-zsh
# 问题描述
目前进行 Web 开发工作，以前一直使用 vscode ，最近接触并了解到 emacs，被其强大的能力所吸引，因此想将后续开发都转为使用 emacs，目前遇到的情况是：
1. 编写 JavaScript 代码时需要自动补全，了解到有多种 mode 可以安装、设置，不知道如何才是最优
2. 完善的 React，Vue 支持需要如何配置
3. 个人 dotfile 配置是基于 zsh 的，是否有必要转为 bash 才能在 emacs 中更好地使用终端
4. 如何才能配置出 Emacs 下较优/最优的 Web 开发环境

希望斌哥 @redguardtoo 以及各位使用 Emacs 作为日常 Web 开发工具的开发者给予建议或指导，共同交流进步。

**Comment by redguardtoo** [comment]
I use `company-ctags` for code completion and `counsel-etags` for code navigation. 

Since you use my `emacs.d`, all you need to do is,
-  install ctags (either universal ctags or exuberant ctags is fine) through homebrew (https://brew.sh/). 
- Type `ctags --version` in terminal to double check ctags is installed.
- Read README at counsel-etags , copy the `.ctags` in README to `~/.ctags`.
- Add below code into `~/.custom.el` (OPTIONAL, the purpose is to update tags file automatically when you saving code)
- Open and js file in your project,  run `M-x counsel-etags-find-tag-at-point`.
- Done!, Now both code completion and code navigation is working.

To find file in project, run `M-x find-file-in-project-at-point`.
To grep in project, run `M-x counsel-etags-grep`

You can add regular expression to `~/.ctags`, though I already add enough patterns for react and angular.

I also used eacl (https://github.com/redguardtoo/eacl) a lot, check its README.

I do have `lsp-mode` installed. lsp does give me some extra type information. But sometimes it slow down my performance. Without lsp, I might code faster. If you need set up lsp-mode, see https://blog.binchen.org/posts/how-to-speed-up-lsp-mode.html

At this stage, I think you don't need lsp-mode.

**Comment by JMwill** [comment]
Thank you very much, I will configure it right now

**Comment by JMwill** [comment]
I use this configuration for a while, but what if I need code completion of third part node_modules?

**Comment by redguardtoo** [comment]
https://github.com/redguardtoo/company-ctags#load-extra-tags-files
